### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by davidstellini** [Ledragon/bar#1]
Hi,

I'm also having issues navigating to an NG1 state from an NG2 component.
`upgradeAdapter.upgradeNg1Provider("$state");` clearly won't cut it. Did you make any progress?

**Comment by davidstellini** [comment]
Nevermind, found out about the ui-router-ng1-to-ng2 project!

**Comment by Ledragon** [comment]
Hi,
Just saw the issue, sorry :\
You can also check [this](https://github.com/SamVerschueren/angular2-polyfill) project to help fill the gap
